name: Fuzzing

on:
  push:
    branches:
      - master

jobs:
  fuzzing:
    name: Run Fuzzer
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t httplib_fuzzer .

    - name: Run the fuzzer and collect logs
      run: |
        CONTAINER_ID=$(docker run --rm -d httplib_fuzzer)
        echo "Waiting for container $CONTAINER_ID to finish..."
        docker wait $CONTAINER_ID
        docker logs $CONTAINER_ID > ./fuzz_logs.txt


    - name: Upload fuzzer logs as artifact
      uses: actions/upload-artifact@v2
      with:
        name: fuzzer-logs
        path: fuzz_logs.txt


