name: Fuzzing CI

on: [push]

jobs:
  fuzzing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker Image
      run: docker build -t httplib_fuzzing_image .

    - name: Run Fuzzer with Timeout and Save Log
      run: |
        docker run --name httplib_fuzzer_container httplib_fuzzing_image /httplib_fuzzer -max_total_time=600 > fuzzing_output.log 2>&1

    - name: Upload Fuzzing Log as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: fuzzing-log
        path: fuzzing_output.log


