name: Fuzzing

on:
  push:
    branches:
      - master

jobs:
  fuzzing:
    name: Run Fuzzer
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t httplib_fuzzer .

    - name: Run the fuzzer and collect logs
      run: docker run httplib_fuzzer > ./fuzz_logs.txt 2>&1

    - name: Upload fuzzer logs as artifact
      uses: actions/upload-artifact@v2
      with:
        name: fuzzer-logs
        path: fuzz_logs.txt


